import jsPDF from 'jspdf';
import { ChatSession } from '../types';

export function exportChatToPdf(chat: ChatSession, userName: string = 'User') {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = 20;

  // Header styling
  doc.setFillColor(15, 23, 42); // Deep slate
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(56, 189, 248); // Cyan
  doc.text('AETHER AI CONVERSATION TRANSCRIPT', margin, 14);

  // Subtitle / Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // Muted slate
  const dateStr = new Date(chat.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  doc.text(`Topic: ${chat.title}  |  Exported: ${dateStr}  |  User: ${userName}`, margin, 21);

  yPosition = 38;

  // Loop messages
  chat.messages.forEach((msg, idx) => {
    const isUser = msg.role === 'user';
    const roleName = isUser ? userName : 'Aether AI (Assistant)';
    
    // Check page overflow
    if (yPosition > 260) {
      doc.addPage();
      yPosition = 20;
    }

    // Role banner
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    if (isUser) {
      doc.setTextColor(168, 85, 247); // Purple
    } else {
      doc.setTextColor(6, 182, 212); // Cyan
    }
    doc.text(`[${roleName}]`, margin, yPosition);
    yPosition += 6;

    // Message Body
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59); // Dark text for PDF readability

    // Clean markdown hashes/backticks lightly for clean document flow
    const cleanText = msg.content
      .replace(/```[a-z]*\n?/gi, '')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1');

    const lines = doc.splitTextToSize(cleanText, contentWidth);
    
    for (let i = 0; i < lines.length; i++) {
      if (yPosition > 275) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(lines[i], margin, yPosition);
      yPosition += 5.2;
    }

    yPosition += 6; // Spacing between messages

    // Thin separator line
    if (idx < chat.messages.length - 1) {
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
      yPosition += 4;
    }
  });

  // Footer page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${i} of ${totalPages} • Generated by Aether AI Assistant`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  // Save the PDF
  const filename = `${chat.title.toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 30)}_transcript.pdf`;
  doc.save(filename);
}
